// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authorization.proto

package ir.micser.login.business.service.authorization.grpc;

public final class AuthorizationOuterClass {
  private AuthorizationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CheckAccessRequestModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CheckAccessRequestModel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string accessToken = 1;</code>
     */
    java.lang.String getAccessToken();
    /**
     * <code>string accessToken = 1;</code>
     */
    com.google.protobuf.ByteString
        getAccessTokenBytes();

    /**
     * <pre>
     *  MethodEnum method = 3;
     * </pre>
     *
     * <code>string url = 2;</code>
     */
    java.lang.String getUrl();
    /**
     * <pre>
     *  MethodEnum method = 3;
     * </pre>
     *
     * <code>string url = 2;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();
  }
  /**
   * Protobuf type {@code CheckAccessRequestModel}
   */
  public  static final class CheckAccessRequestModel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CheckAccessRequestModel)
      CheckAccessRequestModelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CheckAccessRequestModel.newBuilder() to construct.
    private CheckAccessRequestModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CheckAccessRequestModel() {
      accessToken_ = "";
      url_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CheckAccessRequestModel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              accessToken_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              url_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.internal_static_CheckAccessRequestModel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.internal_static_CheckAccessRequestModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel.class, ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel.Builder.class);
    }

    public static final int ACCESSTOKEN_FIELD_NUMBER = 1;
    private volatile java.lang.Object accessToken_;
    /**
     * <code>string accessToken = 1;</code>
     */
    public java.lang.String getAccessToken() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accessToken_ = s;
        return s;
      }
    }
    /**
     * <code>string accessToken = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAccessTokenBytes() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accessToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int URL_FIELD_NUMBER = 2;
    private volatile java.lang.Object url_;
    /**
     * <pre>
     *  MethodEnum method = 3;
     * </pre>
     *
     * <code>string url = 2;</code>
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *  MethodEnum method = 3;
     * </pre>
     *
     * <code>string url = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAccessTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, accessToken_);
      }
      if (!getUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, url_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAccessTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, accessToken_);
      }
      if (!getUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, url_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel)) {
        return super.equals(obj);
      }
      ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel other = (ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel) obj;

      boolean result = true;
      result = result && getAccessToken()
          .equals(other.getAccessToken());
      result = result && getUrl()
          .equals(other.getUrl());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACCESSTOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getAccessToken().hashCode();
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CheckAccessRequestModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CheckAccessRequestModel)
        ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.internal_static_CheckAccessRequestModel_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.internal_static_CheckAccessRequestModel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel.class, ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel.Builder.class);
      }

      // Construct using ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        accessToken_ = "";

        url_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.internal_static_CheckAccessRequestModel_descriptor;
      }

      @java.lang.Override
      public ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel getDefaultInstanceForType() {
        return ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel.getDefaultInstance();
      }

      @java.lang.Override
      public ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel build() {
        ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel buildPartial() {
        ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel result = new ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel(this);
        result.accessToken_ = accessToken_;
        result.url_ = url_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel) {
          return mergeFrom((ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel other) {
        if (other == ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel.getDefaultInstance()) return this;
        if (!other.getAccessToken().isEmpty()) {
          accessToken_ = other.accessToken_;
          onChanged();
        }
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object accessToken_ = "";
      /**
       * <code>string accessToken = 1;</code>
       */
      public java.lang.String getAccessToken() {
        java.lang.Object ref = accessToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accessToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string accessToken = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAccessTokenBytes() {
        java.lang.Object ref = accessToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accessToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string accessToken = 1;</code>
       */
      public Builder setAccessToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        accessToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string accessToken = 1;</code>
       */
      public Builder clearAccessToken() {
        
        accessToken_ = getDefaultInstance().getAccessToken();
        onChanged();
        return this;
      }
      /**
       * <code>string accessToken = 1;</code>
       */
      public Builder setAccessTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        accessToken_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object url_ = "";
      /**
       * <pre>
       *  MethodEnum method = 3;
       * </pre>
       *
       * <code>string url = 2;</code>
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *  MethodEnum method = 3;
       * </pre>
       *
       * <code>string url = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *  MethodEnum method = 3;
       * </pre>
       *
       * <code>string url = 2;</code>
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  MethodEnum method = 3;
       * </pre>
       *
       * <code>string url = 2;</code>
       */
      public Builder clearUrl() {
        
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  MethodEnum method = 3;
       * </pre>
       *
       * <code>string url = 2;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        url_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CheckAccessRequestModel)
    }

    // @@protoc_insertion_point(class_scope:CheckAccessRequestModel)
    private static final ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel();
    }

    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CheckAccessRequestModel>
        PARSER = new com.google.protobuf.AbstractParser<CheckAccessRequestModel>() {
      @java.lang.Override
      public CheckAccessRequestModel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CheckAccessRequestModel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CheckAccessRequestModel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CheckAccessRequestModel> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessRequestModel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CheckAccessResponseModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CheckAccessResponseModel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string result = 1;</code>
     */
    java.lang.String getResult();
    /**
     * <code>string result = 1;</code>
     */
    com.google.protobuf.ByteString
        getResultBytes();

    /**
     * <code>int32 resultCode = 2;</code>
     */
    int getResultCode();

    /**
     * <code>int64 checkDate = 3;</code>
     */
    long getCheckDate();
  }
  /**
   * Protobuf type {@code CheckAccessResponseModel}
   */
  public  static final class CheckAccessResponseModel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CheckAccessResponseModel)
      CheckAccessResponseModelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CheckAccessResponseModel.newBuilder() to construct.
    private CheckAccessResponseModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CheckAccessResponseModel() {
      result_ = "";
      resultCode_ = 0;
      checkDate_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CheckAccessResponseModel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              result_ = s;
              break;
            }
            case 16: {

              resultCode_ = input.readInt32();
              break;
            }
            case 24: {

              checkDate_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.internal_static_CheckAccessResponseModel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.internal_static_CheckAccessResponseModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel.class, ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private volatile java.lang.Object result_;
    /**
     * <code>string result = 1;</code>
     */
    public java.lang.String getResult() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        result_ = s;
        return s;
      }
    }
    /**
     * <code>string result = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULTCODE_FIELD_NUMBER = 2;
    private int resultCode_;
    /**
     * <code>int32 resultCode = 2;</code>
     */
    public int getResultCode() {
      return resultCode_;
    }

    public static final int CHECKDATE_FIELD_NUMBER = 3;
    private long checkDate_;
    /**
     * <code>int64 checkDate = 3;</code>
     */
    public long getCheckDate() {
      return checkDate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResultBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, result_);
      }
      if (resultCode_ != 0) {
        output.writeInt32(2, resultCode_);
      }
      if (checkDate_ != 0L) {
        output.writeInt64(3, checkDate_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResultBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, result_);
      }
      if (resultCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, resultCode_);
      }
      if (checkDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, checkDate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel)) {
        return super.equals(obj);
      }
      ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel other = (ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel) obj;

      boolean result = true;
      result = result && getResult()
          .equals(other.getResult());
      result = result && (getResultCode()
          == other.getResultCode());
      result = result && (getCheckDate()
          == other.getCheckDate());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult().hashCode();
      hash = (37 * hash) + RESULTCODE_FIELD_NUMBER;
      hash = (53 * hash) + getResultCode();
      hash = (37 * hash) + CHECKDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCheckDate());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CheckAccessResponseModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CheckAccessResponseModel)
        ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.internal_static_CheckAccessResponseModel_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.internal_static_CheckAccessResponseModel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel.class, ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel.Builder.class);
      }

      // Construct using ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        result_ = "";

        resultCode_ = 0;

        checkDate_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.internal_static_CheckAccessResponseModel_descriptor;
      }

      @java.lang.Override
      public ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel getDefaultInstanceForType() {
        return ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel.getDefaultInstance();
      }

      @java.lang.Override
      public ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel build() {
        ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel buildPartial() {
        ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel result = new ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel(this);
        result.result_ = result_;
        result.resultCode_ = resultCode_;
        result.checkDate_ = checkDate_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel) {
          return mergeFrom((ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel other) {
        if (other == ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel.getDefaultInstance()) return this;
        if (!other.getResult().isEmpty()) {
          result_ = other.result_;
          onChanged();
        }
        if (other.getResultCode() != 0) {
          setResultCode(other.getResultCode());
        }
        if (other.getCheckDate() != 0L) {
          setCheckDate(other.getCheckDate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object result_ = "";
      /**
       * <code>string result = 1;</code>
       */
      public java.lang.String getResult() {
        java.lang.Object ref = result_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          result_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string result = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResultBytes() {
        java.lang.Object ref = result_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          result_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string result = 1;</code>
       */
      public Builder setResult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string result = 1;</code>
       */
      public Builder clearResult() {
        
        result_ = getDefaultInstance().getResult();
        onChanged();
        return this;
      }
      /**
       * <code>string result = 1;</code>
       */
      public Builder setResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        result_ = value;
        onChanged();
        return this;
      }

      private int resultCode_ ;
      /**
       * <code>int32 resultCode = 2;</code>
       */
      public int getResultCode() {
        return resultCode_;
      }
      /**
       * <code>int32 resultCode = 2;</code>
       */
      public Builder setResultCode(int value) {
        
        resultCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 resultCode = 2;</code>
       */
      public Builder clearResultCode() {
        
        resultCode_ = 0;
        onChanged();
        return this;
      }

      private long checkDate_ ;
      /**
       * <code>int64 checkDate = 3;</code>
       */
      public long getCheckDate() {
        return checkDate_;
      }
      /**
       * <code>int64 checkDate = 3;</code>
       */
      public Builder setCheckDate(long value) {
        
        checkDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 checkDate = 3;</code>
       */
      public Builder clearCheckDate() {
        
        checkDate_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CheckAccessResponseModel)
    }

    // @@protoc_insertion_point(class_scope:CheckAccessResponseModel)
    private static final ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel();
    }

    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CheckAccessResponseModel>
        PARSER = new com.google.protobuf.AbstractParser<CheckAccessResponseModel>() {
      @java.lang.Override
      public CheckAccessResponseModel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CheckAccessResponseModel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CheckAccessResponseModel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CheckAccessResponseModel> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.CheckAccessResponseModel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Empty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code Empty}
   */
  public  static final class Empty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Empty)
      EmptyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Empty.newBuilder() to construct.
    private Empty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Empty() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Empty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.internal_static_Empty_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.internal_static_Empty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty.class, ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty)) {
        return super.equals(obj);
      }
      ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty other = (ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Empty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Empty)
        ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.EmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.internal_static_Empty_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.internal_static_Empty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty.class, ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty.Builder.class);
      }

      // Construct using ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.internal_static_Empty_descriptor;
      }

      @java.lang.Override
      public ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty getDefaultInstanceForType() {
        return ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty.getDefaultInstance();
      }

      @java.lang.Override
      public ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty build() {
        ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty buildPartial() {
        ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty result = new ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty) {
          return mergeFrom((ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty other) {
        if (other == ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Empty)
    }

    // @@protoc_insertion_point(class_scope:Empty)
    private static final ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty();
    }

    public static ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Empty>
        PARSER = new com.google.protobuf.AbstractParser<Empty>() {
      @java.lang.Override
      public Empty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Empty(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Empty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Empty> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ir.micser.login.business.service.authorization.grpc.AuthorizationOuterClass.Empty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CheckAccessRequestModel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CheckAccessRequestModel_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CheckAccessResponseModel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CheckAccessResponseModel_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023authorization.proto\";\n\027CheckAccessRequ" +
      "estModel\022\023\n\013accessToken\030\001 \001(\t\022\013\n\003url\030\002 \001" +
      "(\t\"Q\n\030CheckAccessResponseModel\022\016\n\006result" +
      "\030\001 \001(\t\022\022\n\nresultCode\030\002 \001(\005\022\021\n\tcheckDate\030" +
      "\003 \001(\003\"\007\n\005Empty2S\n\rAuthorization\022B\n\013check" +
      "Access\022\030.CheckAccessRequestModel\032\031.Check" +
      "AccessResponseModelB5\n3ir.micser.login.b" +
      "usiness.service.authorization.grpcb\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CheckAccessRequestModel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CheckAccessRequestModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CheckAccessRequestModel_descriptor,
        new java.lang.String[] { "AccessToken", "Url", });
    internal_static_CheckAccessResponseModel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CheckAccessResponseModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CheckAccessResponseModel_descriptor,
        new java.lang.String[] { "Result", "ResultCode", "CheckDate", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
